events {}

http {
    server {
        listen 80;

        # Registry
        location /v2/ {
            proxy_pass http://registry:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # PGAdmin
        location /pgadmin/ {
            proxy_pass http://pgadmin/pgadmin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Script-Name /pgadmin;
        }
    }
}