events {}

http {
    server {
        listen 80;

        # Frontend
        location / {
        proxy_pass http://rp_frontend:80;
        proxy_set_header Host $host;
        }

        # Swagger UI
        location /api/openapi.json {
            proxy_pass http://rp_backend:8000/api/openapi.json;
            proxy_set_header Host $host;
            add_header Content-Type application/json;
        }
    
        # Backend API
        location /api/ {
            proxy_pass http://rp_backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Registry
        location /v2/ {
            proxy_pass http://rp_registry:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # PGAdmin
        location /pgadmin/ {
            proxy_pass http://rp_pgadmin/pgadmin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Script-Name /pgadmin;
        }
    }
}